In [27]:
import numpy as np
age = np.array([24,21,20,18])# give the elements in the list in normal braces
age

array([24, 21, 20, 18])

In [3]:
age = np.array([[24],[21],[20],[18]])
age

array([[24],
       [21],
       [20],
       [18]])

In [9]:
data=np.array([[24,170,50],[21,165,45],[20,167,50],[18,158,52]])
print("array of age,height,weight\n",data)

array of age,height,weight
 [[ 24 170  50]
 [ 21 165  45]
 [ 20 167  50]
 [ 18 158  52]]


In [11]:
#rows and columns
data.shape

(4, 3)

In [15]:
# i need only age so age is in 0th column and which column (row,columns(n-1))
data[ : ,0:1] # age (0,0) so n-1=1-1=0
print("ages:\n" ,data[:,0:1])

ages:
 [[24]
 [21]
 [20]
 [18]]


In [19]:
# now statistical values
print("*** Statistics for ages ***")
print("Mean:",np.mean(data[:,0:1]))
print("Median:",np.median(data[:,0:1]))
print("std:",np.std(data[:,0:1]))
print("var:",np.var(data[:,0:1]))
print("Min:",np.min(data[:,0:1]))
print("Max:",np.max(data[:,0:1]))
#print("Mode:",np.mode(data[:,0:1])) # we dont have mode in numpy library so we will get error

*** Statistics for ages ***
Mean: 20.75
Median: 20.5
std: 2.165063509461097
var: 4.6875
Min: 18
Max: 24


In [25]:
#heights - height is in (1,1) column 1 is 1st row and 2 is for n-1 its like slicing the array  
data[:,1:2]
print("heights:\n",data[:,1:2])

heights:
 [[170]
 [165]
 [167]
 [158]]


In [23]:
# now statistical values
print("*** Statistics for heights ***")
print("Mean:",np.mean(data[:,1:2]))
print("Median:",np.median(data[:,1:2]))
print("std:",np.std(data[:,1:2]))
print("var:",np.var(data[:,1:2]))
print("Min:",np.min(data[:,1:2]))
print("Max:",np.max(data[:,1:2]))
#print("Mode:",np.mode(data[:,0:1])) # we dont have mode in numpy library so we will get error

*** Statistics for heights ***
Mean: 165.0
Median: 166.0
std: 4.415880433163924
var: 19.5
Min: 158
Max: 170


In [33]:
random=np.random.randint(10,100,size=10) # for random integers int the form of an array 
random

array([98, 90, 35, 30, 17, 90, 49, 84, 96, 37])

In [48]:
random.ndim

1

In [46]:
ran=np.random.randint(10,100,size=(3,4)) #for random 2d array in size we are giving how many rows and columns
ran

array([[20, 76, 27, 45],
       [41, 97, 26, 36],
       [51, 56, 72, 82]])

In [44]:
ran.ndim

2

In [54]:
otp=np.random.randint(1000,9999,size=1)
otp

array([7443])

In [58]:
type(data)

numpy.ndarray

In [56]:
import pandas as pd

In [60]:
df=pd.DataFrame(data)
df

0    1   2
0  24  170  50
1  21  165  45
2  20  167  50
3  18  158  52

In [62]:
type(df)

pandas.core.frame.DataFrame

In [64]:
df.columns=["age","height","weight"]
df

age  height  weight
0   24     170      50
1   21     165      45
2   20     167      50
3   18     158      52

In [66]:
df[["age"]].describe()

age
count   4.00
mean   20.75
std     2.50
min    18.00
25%    19.50
50%    20.50
75%    21.75
max    24.00

In [76]:
df.describe()

age     height     weight
count   4.00    4.00000   4.000000
mean   20.75  165.00000  49.250000
std     2.50    5.09902   2.986079
min    18.00  158.00000  45.000000
25%    19.50  163.25000  48.750000
50%    20.50  166.00000  50.000000
75%    21.75  167.75000  50.500000
max    24.00  170.00000  52.000000

In [78]:
df.isnull()

age  height  weight
0  False   False   False
1  False   False   False
2  False   False   False
3  False   False   False